name: Release Test
run-name: ${{ github.actor }} is deploying release ${{ github.ref_name }}.
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo ref_name
        run: echo "${{ github.ref_name }}"
